#!/usr/bin/env bash
# shellcheck disable=SC2154

# Configures a new Ubuntu machine with Nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Allow Nginx Full in UFW
sudo ufw allow 'Nginx Full'

# Create index page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx site to redirect and add custom header
new_string="listen 80 default_server;
\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com/;
\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
new_string="listen 80 default_server;
error_page 404 /404.html;
\tlocation = /404.html {
\t\troot /usr/share/nginx/html;
\t\tinternal;
\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Add custom header in Nginx configuration
new_string2="http {
\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf

# Start Nginx service
sudo service nginx start
