#!/usr/bin/env bash
#configure nginx server to listen for port 80
#this is spam
#this is spam
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
