#!/usr/bin/env bash
#displays "best school" 10 times using while loop.
#on the 9th iteration, display "hi" before "best school"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
