#!/usr/bin/env bash
#display the contacts of the current directory un list format
#only displays the part of the name after the first dash

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
