#!/usr/bin/env bash
#display unformation about the 'school' file

if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi 

	if [ -f "school" ]
	then
		echo "school is a regularfile"
	fi
else
	echo "school file does not exits"
fi
