#!/usr/bin/env bash

# Create a backup of the original Nginx configuration file
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Replace occurrences of "user root" with "user nginx" in the Nginx configuration
sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
service nginx restart

# Output the Nginx processes and check if it's listening on port 8080
ps auxff | grep ngin[x]
nc -z 0 8080 ; echo $?
